name: binder-environment
channels:
  - conda-forge
dependencies:
  # Enforce Python version
  - python=3.12

  # Scientific python
  - jupyterlab
  - networkx
  - numpy
  - openpyxl
  - pandas
  - scipy

  # Plotting
  - ipympl
  - matplotlib-base
  - plotly
  - seaborn

  # Machine learning
  - scikit-learn

  # General chemistry
  - ase
  - chemiscope
  - mdanalysis
  - mendeleev
  - mordred
  - nglview
  - openmm
  - rdkit

  # Materials Project
  - mp-api
  - mpcontribs-client
  - pymatgen

  # Utilities
  - pycodestyle
  - ruff

  # For study of biosystems
  - deepmd-kit
  - lammps

  # Install some things through pip
  - pip
  # - pip:
  #   - some-pypi-package
